#!/bin/bash

KEY="~/.ssh/ameyaDB"

if [ -z "$1" ]; then
    echo "usage: ./deploy <node_id>"
    exit 1
fi

NODE=$1

# apply infrastructure
cd terraform
terraform apply -auto-approve
BASTION=$(terraform output -raw bastion_ip)
cd ..

ssh -A -i $KEY -o StrictHostKeyChecking=no \
    -J ec2-user@$BASTION ec2-user@node-${NODE}.ameyadb.internal \
    "sudo yum install -y git > /dev/null 2>&1 && \
     if [ -d ameyaDB ]; then cd ameyaDB && git pull; else git clone https://github.com/uhhmeya/ameyaDB ameyaDB && cd ameyaDB; fi && \
     cd engine/src && \
     g++ -o node main.cpp -I/usr/local/include -L/usr/local/lib64 -laws-cpp-sdk-sns -laws-cpp-sdk-sqs -laws-cpp-sdk-core -laws-crt-cpp -laws-c-auth -laws-c-http -laws-c-io -laws-c-common -lpthread -Wl,-rpath,/usr/local/lib64 && \
     ./node ${NODE}"